/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appli_etudiants;

import java.awt.Color;
import java.security.NoSuchAlgorithmException;

/**
 *
 * @author Sara
 */
public class ChangerMdp extends javax.swing.JDialog {

    /**
     * Creates new form ChangerMotDePasse
     */
    public ChangerMdp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //positionnement au milieu de la fenetre parente
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelEtatMdp = new javax.swing.JLabel();
        jButtonChangerMotDePasse = new javax.swing.JButton();
        jPasswordFieldConfirmMdp = new javax.swing.JPasswordField();
        jPasswordFieldMdp = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("<html>Nouveau mot de passe :<br/> (6 caractères minimum)</html>");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Confirmer mot de passe :");

        jLabelEtatMdp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelEtatMdp.setText("...");

        jButtonChangerMotDePasse.setText("Valider");
        jButtonChangerMotDePasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangerMotDePasseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEtatMdp)
                    .addComponent(jPasswordFieldMdp)
                    .addComponent(jPasswordFieldConfirmMdp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonChangerMotDePasse)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordFieldMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPasswordFieldConfirmMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelEtatMdp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButtonChangerMotDePasse)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChangerMotDePasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangerMotDePasseActionPerformed
        /**
         * test que le mot de passe soit valable et le rentre dans la
         */
        System.out.println(this.jPasswordFieldMdp.getText());
        System.out.println(this.jPasswordFieldConfirmMdp.getText());
        if (this.jPasswordFieldMdp.getText().length() >= 6) {
            if (this.jPasswordFieldMdp.getText().equals(this.jPasswordFieldConfirmMdp.getText())) {
                try {
                    String motdepasse = Outils.md5(this.jPasswordFieldMdp.getText());
                    String requeteSql = "update utilisateurs set mot_de_passe ='" + motdepasse + "' where id_utilisateur=" + Connexion.getProfilConnecte().getId();
                    Integer resRequete = BddConnect.requeteAction(requeteSql);
                    if (resRequete == 0) {
                        this.jLabelEtatMdp.setForeground(Color.red);
                        this.jLabelEtatMdp.setText("Echec de la modification");
                    } else {
                        this.jLabelEtatMdp.setForeground(Color.green);
                        this.jLabelEtatMdp.setText("Modification effectuée");
                    }
                } catch (NoSuchAlgorithmException e) {
                    System.out.println("Erreur convertion md5 : " + e);
                }
            } else {
                this.jLabelEtatMdp.setForeground(Color.red);
                this.jLabelEtatMdp.setText("<html>Les mots de passes <br/>doivent être identiques<html>");
            }
        } else {
            this.jLabelEtatMdp.setForeground(Color.red);
            this.jLabelEtatMdp.setText("Mot de passe trop court");
        }

    }//GEN-LAST:event_jButtonChangerMotDePasseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangerMdp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangerMdp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangerMdp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangerMdp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChangerMdp dialog = new ChangerMdp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChangerMotDePasse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEtatMdp;
    private javax.swing.JPasswordField jPasswordFieldConfirmMdp;
    private javax.swing.JPasswordField jPasswordFieldMdp;
    // End of variables declaration//GEN-END:variables
}
