/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appli_etudiants;

import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author Sara
 */
public class CreerEmploye extends javax.swing.JDialog {

    /**
     * Creates new form CreerEmploye
     */
    public CreerEmploye(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //positionnement au milieu de la fenetre parente
        this.setLocationRelativeTo(parent);
        Integer date = new Date().getYear() + 1900;
        this.jTextFieldGererAnneeEntree.setText(date.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldGererAdresseRue1 = new javax.swing.JTextField();
        jTextFieldGererAdresseCp1 = new javax.swing.JTextField();
        jTextFieldGererAdresseVille1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldGererTelPro1 = new javax.swing.JTextField();
        jTextFieldGererAdresseRue = new javax.swing.JTextField();
        jTextFieldGererAdresseCp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldGererAdresseVille = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonCreerValider = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldGererNom = new javax.swing.JTextField();
        jTextFieldGererTelPerso = new javax.swing.JTextField();
        jTextFieldGererPrenom = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldGererMail = new javax.swing.JTextField();
        jTextFieldGererTelPro = new javax.swing.JTextField();
        jLabelEtatModif = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldGererIdentifiant = new javax.swing.JTextField();
        jTextFieldGererSiteWeb = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldGererAnneeEntree = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxPosition = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jComboBoxRole = new javax.swing.JComboBox<>();
        jTextFieldGererMdp = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        jLabel11.setText("Code postal :");

        jLabel12.setText("Ville :");

        jTextFieldGererAdresseRue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGererAdresseRue1ActionPerformed(evt);
            }
        });

        jTextFieldGererAdresseCp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGererAdresseCp1ActionPerformed(evt);
            }
        });

        jTextFieldGererAdresseVille1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGererAdresseVille1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Tel pro :");

        jLabel14.setText("Adresse rue :");

        jTextFieldGererTelPro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGererTelPro1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTextFieldGererAdresseRue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGererAdresseRueActionPerformed(evt);
            }
        });

        jTextFieldGererAdresseCp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGererAdresseCpActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Créer un employé :");

        jTextFieldGererAdresseVille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGererAdresseVilleActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nom :");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Adresse rue :");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Prenom :");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Code postal :");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ville :");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mail :");

        jButtonCreerValider.setText("Créer");
        jButtonCreerValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreerValiderActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tel personnel :");

        jTextFieldGererNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGererNomActionPerformed(evt);
            }
        });

        jTextFieldGererTelPerso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGererTelPersoActionPerformed(evt);
            }
        });

        jTextFieldGererPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGererPrenomActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tel pro :");

        jTextFieldGererMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGererMailActionPerformed(evt);
            }
        });

        jTextFieldGererTelPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGererTelProActionPerformed(evt);
            }
        });

        jLabelEtatModif.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEtatModif.setText("...");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Mot de passe :");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Site web :");

        jTextFieldGererIdentifiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGererIdentifiantActionPerformed(evt);
            }
        });

        jTextFieldGererSiteWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGererSiteWebActionPerformed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Année d'entrée :");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Identifiant :");

        jTextFieldGererAnneeEntree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGererAnneeEntreeActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Position :");

        jComboBoxPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dirigeant", "Cadre", "Non cadre" }));
        jComboBoxPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPositionActionPerformed(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Role :");

        jComboBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Directeur", "Responsable", "Employé" }));
        jComboBoxRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRoleActionPerformed(evt);
            }
        });

        jTextFieldGererMdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGererMdpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jComboBoxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldGererTelPerso, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldGererNom, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldGererPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextFieldGererMail, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))
                            .addComponent(jLabel4))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldGererAnneeEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel18)
                                        .addComponent(jTextFieldGererIdentifiant, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel16)
                                        .addComponent(jTextFieldGererMdp))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17)
                                        .addComponent(jTextFieldGererSiteWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldGererTelPro, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldGererAdresseCp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldGererAdresseRue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jTextFieldGererAdresseVille, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelEtatModif)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCreerValider)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldGererNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldGererPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldGererMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldGererTelPerso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldGererIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldGererMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldGererSiteWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldGererAnneeEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldGererAdresseRue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldGererAdresseCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldGererAdresseVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldGererTelPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEtatModif)
                    .addComponent(jButtonCreerValider))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldGererAdresseRueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGererAdresseRueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGererAdresseRueActionPerformed

    private void jTextFieldGererAdresseCpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGererAdresseCpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGererAdresseCpActionPerformed

    private void jTextFieldGererAdresseVilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGererAdresseVilleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGererAdresseVilleActionPerformed
    /**
     * Permet de tester que tous les champs soient remplis et entrer les
     * informations dans la base de données
     *
     * @param evt
     */
    private void jButtonCreerValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreerValiderActionPerformed
        // TODO add your handling code here:

        //on récupère toutes les données du formulaire
        String CreerNom = this.jTextFieldGererNom.getText();
        String CreerPrenom = this.jTextFieldGererPrenom.getText();
        String CreerMail = this.jTextFieldGererMail.getText();
        String CreerRue = this.jTextFieldGererAdresseRue.getText();
        String CreerVille = this.jTextFieldGererAdresseVille.getText();
        String CreerCp = this.jTextFieldGererAdresseCp.getText();
        String CreerTelPerso = this.jTextFieldGererTelPerso.getText();
        String CreerTelPro = this.jTextFieldGererTelPro.getText();
        String CreerSiteWeb = this.jTextFieldGererSiteWeb.getText();
        String CreerAnneeEntree = this.jTextFieldGererAnneeEntree.getText();
        String CreerIdentifiant = this.jTextFieldGererIdentifiant.getText();
        String CreerMotDePasse = this.jTextFieldGererMdp.getText();
        Integer role = this.jComboBoxRole.getSelectedIndex() + 1;
        Integer position = this.jComboBoxPosition.getSelectedIndex() + 1;

        //on test que toutes les informations soient présentes
        if (CreerNom.length() > 1 && CreerPrenom.length() > 1 && CreerIdentifiant.length() > 1 && CreerMotDePasse.length() > 1
                && CreerMail.length() > 1 && CreerSiteWeb.length() > 1 && CreerAnneeEntree.length() > 1 && CreerCp.length() > 1
                && CreerRue.length() > 1 && CreerVille.length() > 1 && CreerTelPerso.length() > 1 && CreerTelPro.length() > 1) {
            try {
                String motdepasse = Outils.md5(CreerMotDePasse);
                String requeteSql = "insert into utilisateurs  (`id_utilisateur`, `nom`, `prenom`, `adresse_rue`, "
                        + "`adresse_cp`, `adresse_ville`, `tel_personnel`, `tel_professionnel`, `mail`, `site_web`, "
                        + "`annee_entree`, `identifiant`, `mot_de_passe`, `id_role`, `id_grade`) "
                        + "VALUES(NULL,'" + CreerNom + "','" + CreerPrenom + "','" + CreerRue + "',"
                        + CreerCp + ",'" + CreerVille + "'," + CreerTelPerso + "," + CreerTelPro + ",'" + CreerMail + "','"
                        + CreerSiteWeb + "'," + CreerAnneeEntree + ",'" + CreerIdentifiant + "','" + motdepasse + "',"
                        + role + "," + position + ")";
                Integer resRequete = BddConnect.requeteAction(requeteSql);
                if (resRequete == 0) {
                    //this.jLabelEtatModif.setForeground(Color.red);
                    this.jLabelEtatModif.setText("Erreur , l'employé n'a pas pu être crée");
                    System.out.println("requete : " + requeteSql);
                } else {
                    //this.jLabelEtatModif.setForeground(Color.green);
                    this.jLabelEtatModif.setText("Employé crée");
                }
            } catch (NoSuchAlgorithmException e) {
                System.out.println("erreur : " + e);
            }
        } else {
            //this.jLabelEtatModif.setForeground(Color.red);
            this.jLabelEtatModif.setText("Informations manquantes");
        }


    }//GEN-LAST:event_jButtonCreerValiderActionPerformed

    private void jTextFieldGererNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGererNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGererNomActionPerformed

    private void jTextFieldGererTelPersoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGererTelPersoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGererTelPersoActionPerformed

    private void jTextFieldGererPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGererPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGererPrenomActionPerformed

    private void jTextFieldGererMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGererMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGererMailActionPerformed

    private void jTextFieldGererTelProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGererTelProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGererTelProActionPerformed

    private void jTextFieldGererAdresseRue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGererAdresseRue1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGererAdresseRue1ActionPerformed

    private void jTextFieldGererAdresseCp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGererAdresseCp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGererAdresseCp1ActionPerformed

    private void jTextFieldGererAdresseVille1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGererAdresseVille1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGererAdresseVille1ActionPerformed

    private void jTextFieldGererTelPro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGererTelPro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGererTelPro1ActionPerformed

    private void jTextFieldGererIdentifiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGererIdentifiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGererIdentifiantActionPerformed

    private void jTextFieldGererSiteWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGererSiteWebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGererSiteWebActionPerformed

    private void jTextFieldGererAnneeEntreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGererAnneeEntreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGererAnneeEntreeActionPerformed

    private void jComboBoxPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPositionActionPerformed

    private void jComboBoxRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRoleActionPerformed

    private void jTextFieldGererMdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGererMdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGererMdpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreerEmploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreerEmploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreerEmploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreerEmploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreerEmploye dialog = new CreerEmploye(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreerValider;
    private javax.swing.JComboBox<String> jComboBoxPosition;
    private javax.swing.JComboBox<String> jComboBoxRole;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelEtatModif;
    private javax.swing.JTextField jTextFieldGererAdresseCp;
    private javax.swing.JTextField jTextFieldGererAdresseCp1;
    private javax.swing.JTextField jTextFieldGererAdresseRue;
    private javax.swing.JTextField jTextFieldGererAdresseRue1;
    private javax.swing.JTextField jTextFieldGererAdresseVille;
    private javax.swing.JTextField jTextFieldGererAdresseVille1;
    private javax.swing.JTextField jTextFieldGererAnneeEntree;
    private javax.swing.JTextField jTextFieldGererIdentifiant;
    private javax.swing.JTextField jTextFieldGererMail;
    private javax.swing.JTextField jTextFieldGererMdp;
    private javax.swing.JTextField jTextFieldGererNom;
    private javax.swing.JTextField jTextFieldGererPrenom;
    private javax.swing.JTextField jTextFieldGererSiteWeb;
    private javax.swing.JTextField jTextFieldGererTelPerso;
    private javax.swing.JTextField jTextFieldGererTelPro;
    private javax.swing.JTextField jTextFieldGererTelPro1;
    // End of variables declaration//GEN-END:variables
}
