/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appli_etudiants;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Sara
 */
public class GererInfo extends javax.swing.JDialog {

    /**
     * Creates new form GererInfo
     */
    public GererInfo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.jTextFieldGererNom.setText(Connexion.getProfilConnecte().getNom());
        this.jTextFieldGererPrenom.setText(Connexion.getProfilConnecte().getPrenom());
        this.jTextFieldGererMail.setText(Connexion.getProfilConnecte().getCourriel());
        this.jTextFieldGererTelPerso.setText(Connexion.getProfilConnecte().getTelPerso());
        this.jTextFieldGererTelPro.setText(Connexion.getProfilConnecte().getTelPro());
        this.jTextFieldGererAdresseRue.setText(Connexion.getProfilConnecte().getAdresseRue());
        this.jTextFieldGererAdresseVille.setText(Connexion.getProfilConnecte().getAdresseVille());
        this.jTextFieldGererAdresseCp.setText(Connexion.getProfilConnecte().getAdresseCp());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButtonGererInfoValider = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldGererNom = new javax.swing.JTextField();
        jTextFieldGererTelPerso = new javax.swing.JTextField();
        jTextFieldGererPrenom = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldGererMail = new javax.swing.JTextField();
        jTextFieldGererTelPro = new javax.swing.JTextField();
        jTextFieldGererAdresseRue = new javax.swing.JTextField();
        jTextFieldGererAdresseCp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldGererAdresseVille = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelEtatModif = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("Mail :");

        jButtonGererInfoValider.setText("Modifier");
        jButtonGererInfoValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGererInfoValiderActionPerformed(evt);
            }
        });

        jLabel9.setText("Tel personnel :");

        jTextFieldGererNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGererNomActionPerformed(evt);
            }
        });

        jTextFieldGererTelPerso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGererTelPersoActionPerformed(evt);
            }
        });

        jTextFieldGererPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGererPrenomActionPerformed(evt);
            }
        });

        jLabel10.setText("Tel pro :");

        jTextFieldGererMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGererMailActionPerformed(evt);
            }
        });

        jTextFieldGererTelPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGererTelProActionPerformed(evt);
            }
        });

        jTextFieldGererAdresseRue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGererAdresseRueActionPerformed(evt);
            }
        });

        jTextFieldGererAdresseCp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGererAdresseCpActionPerformed(evt);
            }
        });

        jLabel1.setText("Gerer les informations personelles");

        jTextFieldGererAdresseVille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGererAdresseVilleActionPerformed(evt);
            }
        });

        jLabel2.setText("Nom :");

        jLabel6.setText("Adresse rue :");

        jLabel3.setText("Prenom :");

        jLabel7.setText("Code postal :");

        jLabel8.setText("Ville :");

        jLabelEtatModif.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldGererTelPerso, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addComponent(jTextFieldGererTelPro, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelEtatModif)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonGererInfoValider))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldGererNom, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldGererPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldGererAdresseCp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldGererAdresseRue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldGererMail, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jTextFieldGererAdresseVille, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldGererNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGererAdresseRue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldGererPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGererAdresseCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldGererMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGererAdresseVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldGererTelPerso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGererTelPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGererInfoValider)
                    .addComponent(jLabelEtatModif))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGererInfoValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGererInfoValiderActionPerformed
        // TODO add your handling code here:

        //on récupère toutes les données du formulaire
        String modifNom = this.jTextFieldGererNom.getText();
        String modifPrenom = this.jTextFieldGererPrenom.getText();
        String modifMail = this.jTextFieldGererMail.getText();
        String modifRue = this.jTextFieldGererAdresseRue.getText();
        String modifVille = this.jTextFieldGererAdresseVille.getText();
        String modifCp = this.jTextFieldGererAdresseCp.getText();
        String modifTelPerso = this.jTextFieldGererTelPerso.getText();
        String modifTelPro = this.jTextFieldGererTelPro.getText();

        //on crée la requete avec les données
        String requeteSql = "update utilisateurs set "
                + "`nom`='" + modifNom
                + "', `prenom`='" + modifPrenom
                + "', `mail`='" + modifMail
                + "', `adresse_rue`='" + modifRue
                + "', `adresse_ville`='" + modifVille
                + "', `adresse_cp`='" + modifCp
                + "', `tel_personnel`='" + modifTelPerso
                + "',`tel_professionnel`='" + modifTelPro
                + "' where `id_utilisateur`=" + Connexion.getProfilConnecte().getId();

        // on utilise la classe BddConnect pour lancer la requete
        Integer resRequete = BddConnect.requeteAction(requeteSql);
        if (resRequete == 0) {
            this.jLabelEtatModif.setText("Echec de la modification");
            System.out.println(requeteSql);
            this.jLabelEtatModif.setForeground(Color.red);
        } else {
            Connexion.getProfilConnecte().modifPersonne(modifNom, modifPrenom, modifMail, modifRue, modifCp, modifVille, modifTelPerso, modifTelPro);
            this.jLabelEtatModif.setText("Modification réussie");
            this.jLabelEtatModif.setForeground(Color.green);
        }


    }//GEN-LAST:event_jButtonGererInfoValiderActionPerformed

    private void jTextFieldGererNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGererNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGererNomActionPerformed

    private void jTextFieldGererTelPersoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGererTelPersoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGererTelPersoActionPerformed

    private void jTextFieldGererPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGererPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGererPrenomActionPerformed

    private void jTextFieldGererMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGererMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGererMailActionPerformed

    private void jTextFieldGererTelProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGererTelProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGererTelProActionPerformed

    private void jTextFieldGererAdresseRueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGererAdresseRueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGererAdresseRueActionPerformed

    private void jTextFieldGererAdresseCpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGererAdresseCpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGererAdresseCpActionPerformed

    private void jTextFieldGererAdresseVilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGererAdresseVilleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGererAdresseVilleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GererInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GererInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GererInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GererInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GererInfo dialog = new GererInfo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGererInfoValider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelEtatModif;
    private javax.swing.JTextField jTextFieldGererAdresseCp;
    private javax.swing.JTextField jTextFieldGererAdresseRue;
    private javax.swing.JTextField jTextFieldGererAdresseVille;
    private javax.swing.JTextField jTextFieldGererMail;
    private javax.swing.JTextField jTextFieldGererNom;
    private javax.swing.JTextField jTextFieldGererPrenom;
    private javax.swing.JTextField jTextFieldGererTelPerso;
    private javax.swing.JTextField jTextFieldGererTelPro;
    // End of variables declaration//GEN-END:variables
}
