/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package appli_etudiants;

import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;

/**
 *
 * @author nc
 */
public class InterfaceGraphique extends javax.swing.JFrame {

    /**
     * attribut qui indique si l'etudiant est connecté ou non
     */
    private boolean connecte;

    /**
     * interface graphique
     */
    private Connexion fenConnexion;
    private Deconnexion fenDeconnexion;
    private GererInfo fenGererInfo;
    private ChangerMdp fenChangerMdp;
    private CreerEmploye fenCreerEmploye;
    private Promouvoir fenPromouvoir;
    private Retrograder fenRetrograder;

    /**
     * constructeur : Creates new form InterfaceGraphique
     *
     */
    public InterfaceGraphique() {
        initComponents();
        //par defaut, la connexion est inactive
        this.connecte = false;
        //element du menu de deconnexion grisé
        this.majConnexion();
        //centrage
        this.setLocationRelativeTo(null);
        //titre 
        this.setTitle("Gestion des étudiants du bts sio");
        //Par défaut , les vues des utilisateurs sont invisibles
        this.jDesktopPaneEmploye.setVisible(false);
        this.jDesktopPaneResponsable.setVisible(false);
        this.jDesktopPaneDirigeant.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneEmploye = new javax.swing.JDesktopPane();
        jLabelMenuEmploye = new javax.swing.JLabel();
        jButtonGenererCv = new javax.swing.JButton();
        jButtonGererInfo = new javax.swing.JButton();
        jButtonGererFormation = new javax.swing.JButton();
        jLabelPosition = new javax.swing.JLabel();
        jButtonChangerMdpEmploye = new javax.swing.JButton();
        jDesktopPaneResponsable = new javax.swing.JDesktopPane();
        jLabelMenuResponsable = new javax.swing.JLabel();
        jButtonModifierPosition = new javax.swing.JButton();
        jButtonChangerMdpResponsable = new javax.swing.JButton();
        jButtonGenererCv1 = new javax.swing.JButton();
        jButtonGererInfo1 = new javax.swing.JButton();
        jButtonGererFormation1 = new javax.swing.JButton();
        jLabelPositionResp = new javax.swing.JLabel();
        jDesktopPaneDirigeant = new javax.swing.JDesktopPane();
        jLabelMenuDirigeant = new javax.swing.JLabel();
        jButtonCreerEmploye = new javax.swing.JButton();
        jButtonPromouvoir = new javax.swing.JButton();
        jButtonChangerMdpDirigeant = new javax.swing.JButton();
        jButtonGenererCv2 = new javax.swing.JButton();
        jButtonGererInfo2 = new javax.swing.JButton();
        jButtonGererFormation2 = new javax.swing.JButton();
        jButtonRetrograder = new javax.swing.JButton();
        jLabelPositionDir = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButtonConnection = new javax.swing.JButton();
        jButtonInscription = new javax.swing.JButton();
        nomMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        connexionMenuItem = new javax.swing.JMenuItem();
        deconnexionMenuItem = new javax.swing.JMenuItem();
        SortieMenuItem = new javax.swing.JMenuItem();
        aideMenu = new javax.swing.JMenu();
        aproposMenuItem = new javax.swing.JMenuItem();
        nomjMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(320, 400));
        setResizable(false);

        jDesktopPaneEmploye.setBackground(new java.awt.Color(153, 153, 153));
        jDesktopPaneEmploye.setPreferredSize(new java.awt.Dimension(300, 370));

        jLabelMenuEmploye.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMenuEmploye.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMenuEmploye.setText("Employé - ");

        jButtonGenererCv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonGenererCv.setText("Générer un CV");
        jButtonGenererCv.setEnabled(false);
        jButtonGenererCv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenererCvActionPerformed(evt);
            }
        });

        jButtonGererInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonGererInfo.setText("Gerer les informations personelles");
        jButtonGererInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGererInfoActionPerformed(evt);
            }
        });

        jButtonGererFormation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonGererFormation.setText("Gerer les formations");
        jButtonGererFormation.setEnabled(false);

        jLabelPosition.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPosition.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPosition.setText("...");

        jButtonChangerMdpEmploye.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonChangerMdpEmploye.setText("Changer de mot de passe");
        jButtonChangerMdpEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangerMdpEmployeActionPerformed(evt);
            }
        });

        jDesktopPaneEmploye.setLayer(jLabelMenuEmploye, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneEmploye.setLayer(jButtonGenererCv, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneEmploye.setLayer(jButtonGererInfo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneEmploye.setLayer(jButtonGererFormation, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneEmploye.setLayer(jLabelPosition, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneEmploye.setLayer(jButtonChangerMdpEmploye, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout jDesktopPaneEmployeLayout = new org.jdesktop.layout.GroupLayout(jDesktopPaneEmploye);
        jDesktopPaneEmploye.setLayout(jDesktopPaneEmployeLayout);
        jDesktopPaneEmployeLayout.setHorizontalGroup(
            jDesktopPaneEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPaneEmployeLayout.createSequentialGroup()
                .addContainerGap()
                .add(jDesktopPaneEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jDesktopPaneEmployeLayout.createSequentialGroup()
                        .add(jLabelMenuEmploye)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabelPosition))
                    .add(jButtonGenererCv)
                    .add(jButtonGererFormation)
                    .add(jButtonGererInfo)
                    .add(jButtonChangerMdpEmploye))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jDesktopPaneEmployeLayout.setVerticalGroup(
            jDesktopPaneEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPaneEmployeLayout.createSequentialGroup()
                .addContainerGap()
                .add(jDesktopPaneEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelMenuEmploye)
                    .add(jLabelPosition))
                .add(18, 18, 18)
                .add(jButtonGenererCv, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonGererInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonGererFormation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonChangerMdpEmploye, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jDesktopPaneResponsable.setBackground(new java.awt.Color(153, 153, 153));
        jDesktopPaneResponsable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPaneResponsable.setPreferredSize(new java.awt.Dimension(300, 370));

        jLabelMenuResponsable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMenuResponsable.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMenuResponsable.setText("Responsable -");

        jButtonModifierPosition.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonModifierPosition.setText("<html>Modifier la position <br/> d'un employé<html>");
        jButtonModifierPosition.setEnabled(false);
        jButtonModifierPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierPositionActionPerformed(evt);
            }
        });

        jButtonChangerMdpResponsable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonChangerMdpResponsable.setText("Changer de mot de passe");
        jButtonChangerMdpResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangerMdpResponsableActionPerformed(evt);
            }
        });

        jButtonGenererCv1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonGenererCv1.setText("Générer un CV");
        jButtonGenererCv1.setEnabled(false);
        jButtonGenererCv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenererCv1ActionPerformed(evt);
            }
        });

        jButtonGererInfo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonGererInfo1.setText("Gerer les informations personelles");
        jButtonGererInfo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGererInfo1ActionPerformed(evt);
            }
        });

        jButtonGererFormation1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonGererFormation1.setText("Gerer les formations");
        jButtonGererFormation1.setEnabled(false);

        jLabelPositionResp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPositionResp.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPositionResp.setText("...");

        jDesktopPaneResponsable.setLayer(jLabelMenuResponsable, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneResponsable.setLayer(jButtonModifierPosition, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneResponsable.setLayer(jButtonChangerMdpResponsable, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneResponsable.setLayer(jButtonGenererCv1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneResponsable.setLayer(jButtonGererInfo1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneResponsable.setLayer(jButtonGererFormation1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneResponsable.setLayer(jLabelPositionResp, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout jDesktopPaneResponsableLayout = new org.jdesktop.layout.GroupLayout(jDesktopPaneResponsable);
        jDesktopPaneResponsable.setLayout(jDesktopPaneResponsableLayout);
        jDesktopPaneResponsableLayout.setHorizontalGroup(
            jDesktopPaneResponsableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPaneResponsableLayout.createSequentialGroup()
                .addContainerGap()
                .add(jDesktopPaneResponsableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jDesktopPaneResponsableLayout.createSequentialGroup()
                        .add(jLabelMenuResponsable)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabelPositionResp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jButtonModifierPosition, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonChangerMdpResponsable)
                    .add(jButtonGenererCv1)
                    .add(jButtonGererFormation1)
                    .add(jButtonGererInfo1))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jDesktopPaneResponsableLayout.setVerticalGroup(
            jDesktopPaneResponsableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPaneResponsableLayout.createSequentialGroup()
                .addContainerGap()
                .add(jDesktopPaneResponsableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelMenuResponsable)
                    .add(jLabelPositionResp))
                .add(18, 18, 18)
                .add(jButtonGenererCv1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonGererInfo1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonGererFormation1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonModifierPosition, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonChangerMdpResponsable, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jDesktopPaneDirigeant.setBackground(new java.awt.Color(153, 153, 153));
        jDesktopPaneDirigeant.setPreferredSize(new java.awt.Dimension(300, 410));

        jLabelMenuDirigeant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMenuDirigeant.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMenuDirigeant.setText("Directeur");

        jButtonCreerEmploye.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCreerEmploye.setText("Créer un employé");
        jButtonCreerEmploye.setToolTipText("");
        jButtonCreerEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreerEmployeActionPerformed(evt);
            }
        });

        jButtonPromouvoir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPromouvoir.setText("Promouvoir");
        jButtonPromouvoir.setToolTipText("");
        jButtonPromouvoir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPromouvoirActionPerformed(evt);
            }
        });

        jButtonChangerMdpDirigeant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonChangerMdpDirigeant.setText("Changer de mot de passe");
        jButtonChangerMdpDirigeant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangerMdpDirigeantActionPerformed(evt);
            }
        });

        jButtonGenererCv2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonGenererCv2.setText("Générer un CV");
        jButtonGenererCv2.setEnabled(false);
        jButtonGenererCv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenererCv2ActionPerformed(evt);
            }
        });

        jButtonGererInfo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonGererInfo2.setText("Gerer les informations personelles");
        jButtonGererInfo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGererInfo2ActionPerformed(evt);
            }
        });

        jButtonGererFormation2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonGererFormation2.setText("Gerer les formations");
        jButtonGererFormation2.setEnabled(false);

        jButtonRetrograder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonRetrograder.setText("Rétrograder employé");
        jButtonRetrograder.setToolTipText("");
        jButtonRetrograder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetrograderActionPerformed(evt);
            }
        });

        jLabelPositionDir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPositionDir.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPositionDir.setText("...");

        jDesktopPaneDirigeant.setLayer(jLabelMenuDirigeant, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneDirigeant.setLayer(jButtonCreerEmploye, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneDirigeant.setLayer(jButtonPromouvoir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneDirigeant.setLayer(jButtonChangerMdpDirigeant, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneDirigeant.setLayer(jButtonGenererCv2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneDirigeant.setLayer(jButtonGererInfo2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneDirigeant.setLayer(jButtonGererFormation2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneDirigeant.setLayer(jButtonRetrograder, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneDirigeant.setLayer(jLabelPositionDir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout jDesktopPaneDirigeantLayout = new org.jdesktop.layout.GroupLayout(jDesktopPaneDirigeant);
        jDesktopPaneDirigeant.setLayout(jDesktopPaneDirigeantLayout);
        jDesktopPaneDirigeantLayout.setHorizontalGroup(
            jDesktopPaneDirigeantLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPaneDirigeantLayout.createSequentialGroup()
                .addContainerGap()
                .add(jDesktopPaneDirigeantLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButtonChangerMdpDirigeant)
                    .add(jButtonGererFormation2)
                    .add(jButtonGenererCv2)
                    .add(jButtonCreerEmploye)
                    .add(jDesktopPaneDirigeantLayout.createSequentialGroup()
                        .add(jButtonPromouvoir)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonRetrograder))
                    .add(jDesktopPaneDirigeantLayout.createSequentialGroup()
                        .add(jLabelMenuDirigeant)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabelPositionDir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jButtonGererInfo2))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jDesktopPaneDirigeantLayout.setVerticalGroup(
            jDesktopPaneDirigeantLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPaneDirigeantLayout.createSequentialGroup()
                .addContainerGap()
                .add(jDesktopPaneDirigeantLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelMenuDirigeant)
                    .add(jLabelPositionDir))
                .add(18, 18, 18)
                .add(jButtonGenererCv2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonGererInfo2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonGererFormation2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonChangerMdpDirigeant, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonCreerEmploye, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jDesktopPaneDirigeantLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonPromouvoir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonRetrograder, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(320, 370));

        jButtonConnection.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonConnection.setText("Se connecter");
        jButtonConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectionActionPerformed(evt);
            }
        });

        jButtonInscription.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonInscription.setText("Inscription");
        jButtonInscription.setEnabled(false);
        jButtonInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInscriptionActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jButtonConnection, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonInscription, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout jDesktopPane1Layout = new org.jdesktop.layout.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane1Layout.createSequentialGroup()
                .add(68, 68, 68)
                .add(jDesktopPane1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jButtonInscription, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonConnection, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane1Layout.createSequentialGroup()
                .add(90, 90, 90)
                .add(jButtonConnection, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(57, 57, 57)
                .add(jButtonInscription, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("Utilisateur");

        connexionMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        connexionMenuItem.setMnemonic('o');
        connexionMenuItem.setText("Connexion");
        connexionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connexionMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(connexionMenuItem);

        deconnexionMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        deconnexionMenuItem.setMnemonic('s');
        deconnexionMenuItem.setText("Déconnexion");
        deconnexionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnexionMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(deconnexionMenuItem);

        SortieMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SortieMenuItem.setMnemonic('x');
        SortieMenuItem.setText("Sortie");
        SortieMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortieMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(SortieMenuItem);

        nomMenuBar.add(fileMenu);

        aideMenu.setMnemonic('h');
        aideMenu.setText("Aide");

        aproposMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        aproposMenuItem.setMnemonic('c');
        aproposMenuItem.setText("A propos");
        aideMenu.add(aproposMenuItem);

        nomMenuBar.add(aideMenu);
        nomMenuBar.add(nomjMenu);

        setJMenuBar(nomMenuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPaneEmploye, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, jDesktopPaneResponsable, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jDesktopPaneDirigeant, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPaneEmploye, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, jDesktopPaneResponsable, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jDesktopPaneDirigeant, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SortieMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortieMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SortieMenuItemActionPerformed

    private void connexionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connexionMenuItemActionPerformed
        // TODO add your handling code here:

        /**
         * création de la fenetre de connexion et attachement de cette dernière
         * à l'interface maj de connecte en retour
         */
        this.fenConnexion = new Connexion(this, true);
        this.fenConnexion.setVisible(true);

        //JOptionPane.showMessageDialog(this, "cc");
    }//GEN-LAST:event_connexionMenuItemActionPerformed

    private void deconnexionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnexionMenuItemActionPerformed
        // TODO add your handling code here:
        fenDeconnexion = new Deconnexion(this, true);
        this.fenDeconnexion.setVisible(true);
    }//GEN-LAST:event_deconnexionMenuItemActionPerformed

    private void jButtonGenererCvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenererCvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGenererCvActionPerformed

    private void jButtonGererInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGererInfoActionPerformed
        // TODO add your handling code here:
        fenGererInfo = new GererInfo(this, true);
        this.fenGererInfo.setVisible(true);
    }//GEN-LAST:event_jButtonGererInfoActionPerformed

    private void jButtonModifierPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModifierPositionActionPerformed

    private void jButtonCreerEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreerEmployeActionPerformed
        // TODO add your handling code here:
        this.fenCreerEmploye = new CreerEmploye(this, true);
        this.fenCreerEmploye.setVisible(true);
    }//GEN-LAST:event_jButtonCreerEmployeActionPerformed

    private void jButtonPromouvoirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPromouvoirActionPerformed
        // TODO add your handling code here:
        this.fenPromouvoir = new Promouvoir(this, true);
        this.fenPromouvoir.setVisible(true);
    }//GEN-LAST:event_jButtonPromouvoirActionPerformed

    private void jButtonChangerMdpEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangerMdpEmployeActionPerformed
        // TODO add your handling code here:
        this.fenChangerMdp = new ChangerMdp(this, true);
        this.fenChangerMdp.setVisible(true);
    }//GEN-LAST:event_jButtonChangerMdpEmployeActionPerformed

    private void jButtonChangerMdpResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangerMdpResponsableActionPerformed
        // TODO add your handling code here:
        this.fenChangerMdp = new ChangerMdp(this, true);
        this.fenChangerMdp.setVisible(true);
    }//GEN-LAST:event_jButtonChangerMdpResponsableActionPerformed

    private void jButtonChangerMdpDirigeantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangerMdpDirigeantActionPerformed
        // TODO add your handling code here:
        this.fenChangerMdp = new ChangerMdp(this, true);
        this.fenChangerMdp.setVisible(true);
    }//GEN-LAST:event_jButtonChangerMdpDirigeantActionPerformed

    private void jButtonGenererCv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenererCv1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGenererCv1ActionPerformed

    private void jButtonGererInfo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGererInfo1ActionPerformed
        // TODO add your handling code here:
        fenGererInfo = new GererInfo(this, true);
        this.fenGererInfo.setVisible(true);
    }//GEN-LAST:event_jButtonGererInfo1ActionPerformed

    private void jButtonGenererCv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenererCv2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGenererCv2ActionPerformed

    private void jButtonGererInfo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGererInfo2ActionPerformed
        // TODO add your handling code here:
        fenGererInfo = new GererInfo(this, true);
        this.fenGererInfo.setVisible(true);
    }//GEN-LAST:event_jButtonGererInfo2ActionPerformed

    private void jButtonRetrograderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetrograderActionPerformed
        // TODO add your handling code here:
        this.fenRetrograder = new Retrograder(this, true);
        this.fenRetrograder.setVisible(true);
    }//GEN-LAST:event_jButtonRetrograderActionPerformed

    private void jButtonConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectionActionPerformed
        // TODO add your handling code here:
        this.fenConnexion = new Connexion(this, true);
        this.fenConnexion.setVisible(true);
    }//GEN-LAST:event_jButtonConnectionActionPerformed

    private void jButtonInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInscriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInscriptionActionPerformed
    public void connecte(String leNom) {
        //maj de l'etat de la connexion
        this.connecte = true;
        //ajout du nom dans la fenetre
        this.nomjMenu.setText("Connecté en tant que : " + leNom);
        this.nomjMenu.setEnabled(false);

    }

    public void deconnecte() {
        this.connecte = false;
        this.nomjMenu.setText(null);
        this.jDesktopPaneDirigeant.setVisible(false);
        this.jDesktopPaneResponsable.setVisible(false);
        this.jDesktopPaneEmploye.setVisible(false);
    }

    public void majConnexion() {
        deconnexionMenuItem.setEnabled(this.connecte);
        connexionMenuItem.setEnabled(!this.connecte);
    }

    /**
     * rend visible l'interface employé
     */
    public void setInterfaceEmployeVisible() {
        this.jDesktopPaneEmploye.setVisible(true);
        this.jLabelPosition.setText(Connexion.getProfilConnecte().getGrade());
        this.jDesktopPane1.setVisible(false);
    }

    /**
     * rend visible l'interface Responsable
     */
    public void setInterfaceResponsableVisible() {
        this.jDesktopPaneResponsable.setVisible(true);
        this.jLabelPositionResp.setText(Connexion.getProfilConnecte().getGrade());
        this.jDesktopPane1.setVisible(false);

    }

    /**
     * rend visible l'interface Dirigeant
     */
    public void setInterfaceDirigeantVisible() {
        this.jDesktopPaneDirigeant.setVisible(true);
        this.jLabelPositionDir.setText(Connexion.getProfilConnecte().getGrade());
        this.jDesktopPane1.setVisible(false);

    }

    public void setInterfaceConnexionVisible() {
        this.jDesktopPane1.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGraphique().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem SortieMenuItem;
    private javax.swing.JMenu aideMenu;
    private javax.swing.JMenuItem aproposMenuItem;
    private javax.swing.JMenuItem connexionMenuItem;
    private javax.swing.JMenuItem deconnexionMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton jButtonChangerMdpDirigeant;
    private javax.swing.JButton jButtonChangerMdpEmploye;
    private javax.swing.JButton jButtonChangerMdpResponsable;
    private javax.swing.JButton jButtonConnection;
    private javax.swing.JButton jButtonCreerEmploye;
    private javax.swing.JButton jButtonGenererCv;
    private javax.swing.JButton jButtonGenererCv1;
    private javax.swing.JButton jButtonGenererCv2;
    private javax.swing.JButton jButtonGererFormation;
    private javax.swing.JButton jButtonGererFormation1;
    private javax.swing.JButton jButtonGererFormation2;
    private javax.swing.JButton jButtonGererInfo;
    private javax.swing.JButton jButtonGererInfo1;
    private javax.swing.JButton jButtonGererInfo2;
    private javax.swing.JButton jButtonInscription;
    private javax.swing.JButton jButtonModifierPosition;
    private javax.swing.JButton jButtonPromouvoir;
    private javax.swing.JButton jButtonRetrograder;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPaneDirigeant;
    private javax.swing.JDesktopPane jDesktopPaneEmploye;
    private javax.swing.JDesktopPane jDesktopPaneResponsable;
    private javax.swing.JLabel jLabelMenuDirigeant;
    private javax.swing.JLabel jLabelMenuEmploye;
    private javax.swing.JLabel jLabelMenuResponsable;
    private javax.swing.JLabel jLabelPosition;
    private javax.swing.JLabel jLabelPositionDir;
    private javax.swing.JLabel jLabelPositionResp;
    private javax.swing.JMenuBar nomMenuBar;
    private javax.swing.JMenu nomjMenu;
    // End of variables declaration//GEN-END:variables
}
