/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package appli_etudiants;

import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;

/**
 *
 * @author nc
 */
public class InterfaceGraphique extends javax.swing.JFrame {

    /**
     * attribut qui indique si l'etudiant est connecté ou non
     */
    private boolean connecte;

    /**
     * interface graphique
     */
    private Connexion fenConnexion;
    private Deconnexion fenDeconnexion;
    private GererInfo fenGererInfo;
    private ChangerMdp fenChangerMdp;
    private CreerEmploye fenCreerEmploye;
    private Promouvoir fenPromouvoir;

    /**
     * constructeur : Creates new form InterfaceGraphique
     *
     */
    public InterfaceGraphique() {
        initComponents();
        //par defaut, la connexion est inactive
        this.connecte = false;
        //element du menu de deconnexion grisé
        this.majConnexion();
        //centrage
        this.setLocationRelativeTo(null);
        //titre 
        this.setTitle("Gestion des étudiants du bts sio");
        //Par défaut , les vues des utilisateurs sont invisibles
        this.jDesktopPaneEmploye.setVisible(false);
        this.jDesktopPaneResponsable.setVisible(false);
        this.jDesktopPaneDirigeant.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneBase = new javax.swing.JDesktopPane();
        jDesktopPaneEmploye = new javax.swing.JDesktopPane();
        jLabelMenuEmploye = new javax.swing.JLabel();
        jButtonGenererCv = new javax.swing.JButton();
        jButtonGererInfo = new javax.swing.JButton();
        jButtonGererFormation = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelPosition = new javax.swing.JLabel();
        jButtonChangerMdpEmploye = new javax.swing.JButton();
        jDesktopPaneResponsable = new javax.swing.JDesktopPane();
        jLabelMenuResponsable = new javax.swing.JLabel();
        jButtonModifierPosition = new javax.swing.JButton();
        jButtonChangerMdpResponsable = new javax.swing.JButton();
        jDesktopPaneDirigeant = new javax.swing.JDesktopPane();
        jLabelMenuDirigeant = new javax.swing.JLabel();
        jButtonCreerEmploye = new javax.swing.JButton();
        jButtonPromouvoir = new javax.swing.JButton();
        jButtonChangerMdpDirigeant = new javax.swing.JButton();
        nomMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        connexionMenuItem = new javax.swing.JMenuItem();
        deconnexionMenuItem = new javax.swing.JMenuItem();
        SortieMenuItem = new javax.swing.JMenuItem();
        aideMenu = new javax.swing.JMenu();
        aproposMenuItem = new javax.swing.JMenuItem();
        nomjMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.layout.GroupLayout jDesktopPaneBaseLayout = new org.jdesktop.layout.GroupLayout(jDesktopPaneBase);
        jDesktopPaneBase.setLayout(jDesktopPaneBaseLayout);
        jDesktopPaneBaseLayout.setHorizontalGroup(
            jDesktopPaneBaseLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
        jDesktopPaneBaseLayout.setVerticalGroup(
            jDesktopPaneBaseLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        jDesktopPaneEmploye.setBackground(new java.awt.Color(102, 102, 102));

        jLabelMenuEmploye.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMenuEmploye.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMenuEmploye.setText("Utilisateur : employé");

        jButtonGenererCv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonGenererCv.setText("Générer un CV");
        jButtonGenererCv.setEnabled(false);
        jButtonGenererCv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenererCvActionPerformed(evt);
            }
        });

        jButtonGererInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonGererInfo.setText("Gerer les informations personelles");
        jButtonGererInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGererInfoActionPerformed(evt);
            }
        });

        jButtonGererFormation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonGererFormation.setText("Gerer les formations");
        jButtonGererFormation.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Position : ");

        jLabelPosition.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPosition.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPosition.setText("...");

        jButtonChangerMdpEmploye.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonChangerMdpEmploye.setText("Changer de mot de passe");
        jButtonChangerMdpEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangerMdpEmployeActionPerformed(evt);
            }
        });

        jDesktopPaneEmploye.setLayer(jLabelMenuEmploye, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneEmploye.setLayer(jButtonGenererCv, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneEmploye.setLayer(jButtonGererInfo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneEmploye.setLayer(jButtonGererFormation, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneEmploye.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneEmploye.setLayer(jLabelPosition, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneEmploye.setLayer(jButtonChangerMdpEmploye, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout jDesktopPaneEmployeLayout = new org.jdesktop.layout.GroupLayout(jDesktopPaneEmploye);
        jDesktopPaneEmploye.setLayout(jDesktopPaneEmployeLayout);
        jDesktopPaneEmployeLayout.setHorizontalGroup(
            jDesktopPaneEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPaneEmployeLayout.createSequentialGroup()
                .addContainerGap()
                .add(jDesktopPaneEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelMenuEmploye)
                    .add(jButtonGenererCv)
                    .add(jButtonGererFormation)
                    .add(jDesktopPaneEmployeLayout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabelPosition))
                    .add(jButtonGererInfo)
                    .add(jButtonChangerMdpEmploye))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPaneEmployeLayout.setVerticalGroup(
            jDesktopPaneEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPaneEmployeLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelMenuEmploye)
                .add(11, 11, 11)
                .add(jDesktopPaneEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jLabelPosition))
                .add(18, 18, 18)
                .add(jButtonGenererCv, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonGererInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonGererFormation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonChangerMdpEmploye, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPaneResponsable.setBackground(new java.awt.Color(240, 240, 240));
        jDesktopPaneResponsable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPaneResponsable.setPreferredSize(new java.awt.Dimension(191, 89));

        jLabelMenuResponsable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMenuResponsable.setText("Utilisateur : responsable");

        jButtonModifierPosition.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonModifierPosition.setText("<html>Modifier la position <br/> d'un employé<html>");
        jButtonModifierPosition.setEnabled(false);
        jButtonModifierPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierPositionActionPerformed(evt);
            }
        });

        jButtonChangerMdpResponsable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonChangerMdpResponsable.setText("Changer de mot de passe");
        jButtonChangerMdpResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangerMdpResponsableActionPerformed(evt);
            }
        });

        jDesktopPaneResponsable.setLayer(jLabelMenuResponsable, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneResponsable.setLayer(jButtonModifierPosition, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneResponsable.setLayer(jButtonChangerMdpResponsable, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout jDesktopPaneResponsableLayout = new org.jdesktop.layout.GroupLayout(jDesktopPaneResponsable);
        jDesktopPaneResponsable.setLayout(jDesktopPaneResponsableLayout);
        jDesktopPaneResponsableLayout.setHorizontalGroup(
            jDesktopPaneResponsableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPaneResponsableLayout.createSequentialGroup()
                .addContainerGap()
                .add(jDesktopPaneResponsableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelMenuResponsable)
                    .add(jButtonModifierPosition, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonChangerMdpResponsable))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPaneResponsableLayout.setVerticalGroup(
            jDesktopPaneResponsableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPaneResponsableLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelMenuResponsable)
                .add(18, 18, 18)
                .add(jButtonModifierPosition, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonChangerMdpResponsable, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPaneDirigeant.setBackground(new java.awt.Color(240, 240, 240));

        jLabelMenuDirigeant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMenuDirigeant.setText("Utilisateur : dirigeant");

        jButtonCreerEmploye.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCreerEmploye.setText("Créer un employé");
        jButtonCreerEmploye.setToolTipText("");
        jButtonCreerEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreerEmployeActionPerformed(evt);
            }
        });

        jButtonPromouvoir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPromouvoir.setText("Promouvoir employé");
        jButtonPromouvoir.setToolTipText("");
        jButtonPromouvoir.setActionCommand("Promouvoir employé");
        jButtonPromouvoir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPromouvoirActionPerformed(evt);
            }
        });

        jButtonChangerMdpDirigeant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonChangerMdpDirigeant.setText("Changer de mot de passe");
        jButtonChangerMdpDirigeant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangerMdpDirigeantActionPerformed(evt);
            }
        });

        jDesktopPaneDirigeant.setLayer(jLabelMenuDirigeant, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneDirigeant.setLayer(jButtonCreerEmploye, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneDirigeant.setLayer(jButtonPromouvoir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneDirigeant.setLayer(jButtonChangerMdpDirigeant, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout jDesktopPaneDirigeantLayout = new org.jdesktop.layout.GroupLayout(jDesktopPaneDirigeant);
        jDesktopPaneDirigeant.setLayout(jDesktopPaneDirigeantLayout);
        jDesktopPaneDirigeantLayout.setHorizontalGroup(
            jDesktopPaneDirigeantLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPaneDirigeantLayout.createSequentialGroup()
                .addContainerGap()
                .add(jDesktopPaneDirigeantLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelMenuDirigeant)
                    .add(jButtonCreerEmploye)
                    .add(jButtonPromouvoir)
                    .add(jButtonChangerMdpDirigeant))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPaneDirigeantLayout.setVerticalGroup(
            jDesktopPaneDirigeantLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPaneDirigeantLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelMenuDirigeant)
                .add(18, 18, 18)
                .add(jButtonCreerEmploye, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonPromouvoir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonChangerMdpDirigeant, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("Etudiants");

        connexionMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        connexionMenuItem.setMnemonic('o');
        connexionMenuItem.setText("Connexion");
        connexionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connexionMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(connexionMenuItem);

        deconnexionMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        deconnexionMenuItem.setMnemonic('s');
        deconnexionMenuItem.setText("Déconnexion");
        deconnexionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnexionMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(deconnexionMenuItem);

        SortieMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SortieMenuItem.setMnemonic('x');
        SortieMenuItem.setText("Sortie");
        SortieMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortieMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(SortieMenuItem);

        nomMenuBar.add(fileMenu);

        aideMenu.setMnemonic('h');
        aideMenu.setText("Aide");

        aproposMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        aproposMenuItem.setMnemonic('c');
        aproposMenuItem.setText("A propos");
        aideMenu.add(aproposMenuItem);

        nomMenuBar.add(aideMenu);
        nomMenuBar.add(nomjMenu);

        setJMenuBar(nomMenuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPaneEmploye)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, jDesktopPaneResponsable, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jDesktopPaneDirigeant))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jDesktopPaneBase, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPaneEmploye)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, jDesktopPaneResponsable, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jDesktopPaneDirigeant))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jDesktopPaneBase, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SortieMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortieMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SortieMenuItemActionPerformed

    private void connexionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connexionMenuItemActionPerformed
        // TODO add your handling code here:

        /**
         * création de la fenetre de connexion et attachement de cette dernière
         * à l'interface maj de connecte en retour
         */
        this.fenConnexion = new Connexion(this, true);
        this.fenConnexion.setVisible(true);

        //JOptionPane.showMessageDialog(this, "cc");
    }//GEN-LAST:event_connexionMenuItemActionPerformed

    private void deconnexionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnexionMenuItemActionPerformed
        // TODO add your handling code here:
        fenDeconnexion = new Deconnexion(this, true);
        this.fenDeconnexion.setVisible(true);
    }//GEN-LAST:event_deconnexionMenuItemActionPerformed

    private void jButtonGenererCvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenererCvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGenererCvActionPerformed

    private void jButtonGererInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGererInfoActionPerformed
        // TODO add your handling code here:
        fenGererInfo = new GererInfo(this, true);
        this.fenGererInfo.setVisible(true);
    }//GEN-LAST:event_jButtonGererInfoActionPerformed

    private void jButtonModifierPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModifierPositionActionPerformed

    private void jButtonCreerEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreerEmployeActionPerformed
        // TODO add your handling code here:
        this.fenCreerEmploye = new CreerEmploye(this, true);
        this.fenCreerEmploye.setVisible(true);
    }//GEN-LAST:event_jButtonCreerEmployeActionPerformed

    private void jButtonPromouvoirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPromouvoirActionPerformed
        // TODO add your handling code here:
        this.fenPromouvoir=new Promouvoir(this, true);
        this.fenPromouvoir.setVisible(true);
    }//GEN-LAST:event_jButtonPromouvoirActionPerformed

    private void jButtonChangerMdpEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangerMdpEmployeActionPerformed
        // TODO add your handling code here:
        this.fenChangerMdp = new ChangerMdp(this, true);
        this.fenChangerMdp.setVisible(true);
    }//GEN-LAST:event_jButtonChangerMdpEmployeActionPerformed

    private void jButtonChangerMdpResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangerMdpResponsableActionPerformed
        // TODO add your handling code here:
        this.fenChangerMdp = new ChangerMdp(this, true);
        this.fenChangerMdp.setVisible(true);
    }//GEN-LAST:event_jButtonChangerMdpResponsableActionPerformed

    private void jButtonChangerMdpDirigeantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangerMdpDirigeantActionPerformed
        // TODO add your handling code here:
        this.fenChangerMdp = new ChangerMdp(this, true);
        this.fenChangerMdp.setVisible(true);
    }//GEN-LAST:event_jButtonChangerMdpDirigeantActionPerformed
    public void connecte(String leNom) {
        //maj de l'etat de la connexion
        this.connecte = true;
        //ajout du nom dans la fenetre
        this.nomjMenu.setText("Connecté en tant que : " + leNom);
        this.nomjMenu.setEnabled(false);

    }

    public void deconnecte() {
        this.connecte = false;
        this.nomjMenu.setText(null);
        this.jDesktopPaneDirigeant.setVisible(false);
        this.jDesktopPaneResponsable.setVisible(false);
        this.jDesktopPaneEmploye.setVisible(false);
    }

    public void majConnexion() {
        deconnexionMenuItem.setEnabled(this.connecte);
        connexionMenuItem.setEnabled(!this.connecte);
    }

    /**
     * rend visible l'interface employé
     */
    public void setInterfaceEmployeVisible() {
        this.jDesktopPaneEmploye.setVisible(true);
        this.jLabelPosition.setText(Connexion.getProfilConnecte().getGrade());
    }

    /**
     * rend visible l'interface Responsable
     */
    public void setInterfaceResponsableVisible() {
        this.jDesktopPaneResponsable.setVisible(true);
    }

    /**
     * rend visible l'interface Dirigeant
     */
    public void setInterfaceDirigeantVisible() {
        this.jDesktopPaneDirigeant.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGraphique().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem SortieMenuItem;
    private javax.swing.JMenu aideMenu;
    private javax.swing.JMenuItem aproposMenuItem;
    private javax.swing.JMenuItem connexionMenuItem;
    private javax.swing.JMenuItem deconnexionMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton jButtonChangerMdpDirigeant;
    private javax.swing.JButton jButtonChangerMdpEmploye;
    private javax.swing.JButton jButtonChangerMdpResponsable;
    private javax.swing.JButton jButtonCreerEmploye;
    private javax.swing.JButton jButtonGenererCv;
    private javax.swing.JButton jButtonGererFormation;
    private javax.swing.JButton jButtonGererInfo;
    private javax.swing.JButton jButtonModifierPosition;
    private javax.swing.JButton jButtonPromouvoir;
    private javax.swing.JDesktopPane jDesktopPaneBase;
    private javax.swing.JDesktopPane jDesktopPaneDirigeant;
    private javax.swing.JDesktopPane jDesktopPaneEmploye;
    private javax.swing.JDesktopPane jDesktopPaneResponsable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMenuDirigeant;
    private javax.swing.JLabel jLabelMenuEmploye;
    private javax.swing.JLabel jLabelMenuResponsable;
    private javax.swing.JLabel jLabelPosition;
    private javax.swing.JMenuBar nomMenuBar;
    private javax.swing.JMenu nomjMenu;
    // End of variables declaration//GEN-END:variables
}
